version: "3.8"
services:
  frontend:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000" # Webpack Dev Server runs here
    volumes:
      - .:/app # Mount your source code
      - /app/node_modules # Prevent host overwriting container's node_modules
    environment:
      - NODE_ENV=development
