# docker-compose.yml
# ------------------
version: '3.8'
services:
  frontend:
    build:
      context: .
      target: prod
    environment:
      - BASE_URL=http://localhost:8080
    ports:
      - "8080:80"  # Production: NGINX serves on port 80 inside container
    restart: unless-stopped

